[dynamic]
strategy = "simulate"
postpone_routes = false


[dynamic.strategy_params]
strategy_tlim_factor = 0.80
n_cycles = -1
n_simulations = 30
n_lookahead = 1
consensus = "branch_and_regret"


[dynamic.strategy_params.consensus_params]
