[dynamic]
strategy = "simulate"
postpone_routes = false


[dynamic.strategy_params]
strategy_tlim_factor = 0.80
n_cycles = 100
n_simulations = 20
n_lookahead = 1
consensus = "branch_and_regret"


[dynamic.strategy_params.consensus_params]
cost_eval_tlim = 0.2
