[dynamic]
strategy = "simulate"


[dynamic.strategy_params]
strategy_tlim_factor = 0.80
n_cycles = 3
n_simulations = 30
n_lookahead = 1
consensus = "fixed_threshold"
final_dispatch = "to_dispatch"


[dynamic.strategy_params.consensus_params]
postpone_thresholds = [
    1.01, # no postponement
]
dispatch_thresholds = [
    0.50,
]
