[dynamic]
strategy = "simulate"


[dynamic.strategy_params]
strategy_tlim_factor = 0.80
n_cycles = -1
n_simulations = 30
n_lookahead = 1
consensus = "dynamic_stochastic_hedging_heuristic"
final_dispatch = "to_dispatch"


[dynamic.strategy_params.consensus_params]
min_dispatch_threshold = 0.50
dispatch_threshold = 0.70
