[dynamic]
strategy = "simulate"
postpone_routes = false


[dynamic.strategy_params]
simulate_tlim_factor = 0.80
n_cycles = 5
n_simulations = 30
n_lookahead = 1
consensus = "dynamic_stochastic_hedging_heuristic"


[dynamic.strategy_params.consensus_params]
min_dispatch_threshold = 0.50
dispatch_threshold = 0.70
