agent = "icd"

[agent_params]
num_iterations = 3
num_lookahead = 1
num_scenarios = 30
consensus = "fixed_threshold"
dispatch_choice = "not_postpone"

[agent_params.consensus_params]
postpone_threshold = 0.70
dispatch_threshold = 1.01 # don't mark dispatch
