agent = "icd"

[agent_params]
num_iterations = 2
num_lookahead = 4
num_scenarios = 10
consensus = "fixed_threshold"

[agent_params.consensus_params]
postpone_thresholds = [
    0.80,
]
dispatch_thresholds = [
    0.50,
]
