agent = "icd"

[agent_params]
num_iterations = 2
num_lookahead = 1
num_scenarios = 10
consensus = "fixed_threshold"

[agent_params.consensus_params]
postpone_threshold = 0.80
dispatch_threshold = 0.50
