[dynamic]
strategy = "simulate"
postpone_routes = false


[dynamic.strategy_params]
strategy_tlim_factor = 0.80
n_cycles = 3
n_simulations = 30
n_lookahead = 1
consensus = "fixed_threshold"
final_dispatch = "not_to_postpone"


[dynamic.strategy_params.consensus_params]
postpone_thresholds = [
    0.70,
]
dispatch_thresholds = [
    1.01, # only must dispatch
]
