[static]
node_ops = [
    "Exchange10",
    "Exchange11",
    "TwoOpt",
]

route_ops = []

crossover_ops = [
    "selective_route_exchange",
]

[static.params]
seed = 1
initialTimeWarpPenalty = 14
nbPenaltyManagement = 1
feasBooster = 9.045454545454545
penaltyIncrease = 2.0303030303030303
penaltyDecrease = 0.33712121212121215
targetFeasible = 0.18686868686868688
repairProbability = 0
repairBooster = 10
minPopSize = 3
generationSize = 8
shouldIntensify = 0
nbGranular = 16
weightWaitTime = 5
weightTimeWarp = 18
